# References:
#   - https://docs.travis-ci.com/user/customizing-the-build/
#   - https://docs.travis-ci.com/user/pull-requests/

language: node_js

node_js:
  - "8.11.4"

sudo: false

branches:
  only:
    - master
    - develop
    - /^feature\/.*$/

script:
  - npm install
  - npm run test
